{
    'name': 'Login/signup reCAPTCHA',
    'version': '16.0.1.0.0',
    'summary': """Protect robot login and signup with reCAPTCHA""",
    'author': 'Oakland Odoo ERP',
    'company': 'Oakland Odoo ERP',
    'website': 'https://www.odooerp.ae',
    'category': 'Extra Tools',
    'depends': ['base'],
    'images': ['static/description/banner.gif'],
    'license': 'LGPL-3',
    'depends': ['base', 'web', '7md_website'],
    'data': [
        'security/ir.model.access.csv',
        'static/templates/header.xml',
        'views/captcha_views.xml',
        'views/store_location.xml',
        'views/home_page_settings.xml',
        'views/inherit_crm_leads.xml',
        'views/website_category.xml',
        'views/sucess_message_template.xml',
        'static/templates/contact.xml',
        'static/templates/index.xml',
        'static/templates/brand.xml',
        'static/templates/shop_customized_three.xml',
        "static/templates/profile_phone.xml",
        "static/templates/varient_modal.xml"
    ],
    'assets': {
        'web.assets_frontend': [
            "oe_login_signup/static/src/js/add_wishlist.js",
            "oe_login_signup/static/src/js/buy_now.js",
            "oe_login_signup/static/src/js/add_wishlist_home_page.js",
            "oe_login_signup/static/src/js/brand_search.js",
            "oe_login_signup/static/src/js/captcha.js",
            "oe_login_signup/static/src/js/autofill.js",
            "oe_login_signup/static/src/js/js_add_to_cart.js",
            "oe_login_signup/static/src/js/intl.js",
            "oe_login_signup/static/src/css/intl.css",
            "oe_login_signup/static/src/css/font.css",
        ],
    },
    'installable': True,
    'auto_install': False,

}
